# Generated by Django 6.0.6 on 2026-07-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand_product_created_at_product_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='logo',
            new_name='image',
        ),
    ]
