# Generated by Django 6.0.6 on 2026-09-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(choices=[('Party Wear', 'Party Wear'), ('Wedding', 'Wedding'), ('Casual', 'Casual'), ('Office Wear', 'Office Wear'), ('Festive', 'Festive')], default='Casual', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Western', 'Western'), ('Indo-Western', 'Indo-Western')], default='Western', max_length=20),
        ),
    ]
