# Generated by Django 6.0.6 on 2026-09-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_gender_product_occasion_product_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Monsoon', 'Monsoon'), ('Spring', 'Spring'), ('Any', 'Any')], default='Summer', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasion',
            field=models.CharField(choices=[('College', 'College'), ('Office', 'Office'), ('Party', 'Party'), ('Wedding', 'Wedding'), ('Vacation', 'Vacation'), ('Casual', 'Casual'), ('Date', 'Date')], default='Casual', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[('Minimal', 'Minimal'), ('Casual', 'Casual'), ('Korean', 'Korean'), ('Streetwear', 'Streetwear'), ('Elegant', 'Elegant'), ('Trendy', 'Trendy'), ('Formal', 'Formal')], default='Western', max_length=20),
        ),
    ]
