# Generated by Django 6.0.6 on 2026-09-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_season_alter_product_occasion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Example: Black,Red,Blue,Pink', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Example: XS,S,M,L,XL', max_length=200),
        ),
    ]
